### ISSUE TITLE
Having the starter package inside a folder will cause compile errors

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#115]
So far you need to include all your starter bot files directly in the zip, if you have it in a folder first, it will cause the compile to fail:

```
contest@aichallengebeta:~/aichallenge/worker$ python ~/aichallenge/worker/worker.py -t 0 --debug
2011-05-20 23:54:18,943 - 21129 - INFO - Getting task 1
2011-05-20 23:54:18,944 - 21129 - DEBUG - http://hypertriangle.com:13080//api_get_task.php?api_key=a6625962a72a7a3fac59fb34a1fdc504
2011-05-20 23:54:19,070 - 21129 - INFO - Received task: {u'submission_id': u'45', u'task': u'compile'}
2011-05-20 23:54:19,072 - 21129 - INFO - Downloading 45...
2011-05-20 23:54:19,072 - 21129 - DEBUG - http://hypertriangle.com:13080//api_get_submission.php?api_key=a6625962a72a7a3fac59fb34a1fdc504&submission_id=45
2011-05-20 23:54:19,318 - 21129 - INFO - Unpacking /home/contest/compiled/tmpMqeKRx...
2011-05-20 23:54:19,334 - 21129 - INFO - unnzip status: 0
2011-05-20 23:54:19,357 - 21129 - INFO - Compiling 45 
2011-05-20 23:54:19,358 - 21129 - ERROR - {'errors': [], 'language_count': 0}
2011-05-20 23:54:19,359 - 21129 - INFO - http://hypertriangle.com:13080//api_compile_result.php?api_key=a6625962a72a7a3fac59fb34a1fdc504
2011-05-20 23:54:19,359 - 21129 - DEBUG - Posting result api_compile_result: {"post_id": 1, "status_id": 70, "errors": "{\"errors\": [], \"language_count\": 0}", "language": "Unknown", "submission_id": 45}
2011-05-20 23:54:19,359 - 21129 - INFO - Posting hash: 92a12682b5a29869f671cb72dcc44263
2011-05-20 23:54:19,482 - 21129 - DEBUG - {"hash":"92a12682b5a29869f671cb72dcc44263"}
2011-05-20 23:54:19,482 - 21129 - INFO - Server returned hash: 92a12682b5a29869f671cb72dcc44263
2011-05-20 23:54:19,484 - 21129 - ERROR - Compile Error
```

**Comment by aerique** [comment]
If MyBot.ext is directly in a zip but the rest of the sourcefiles are in a subdir, does that work?  This is at least the case for the CL starter pack.

**Comment by McLeopold** [comment]
Starter bots should not be so complicated as to have subfolders.  This functionality is by design and starter bots should meet the spec.

**Comment by aerique** [comment]
This issue is bigger than just starter bots.  When the contest has started and people's code bases are growing they will want to organize those code bases to make them less complicated.  It is only natural to put files into subdirectories then.

Also, could you point me to the spec you're talking about?  The only one I know if is: https://github.com/aichallenge/aichallenge/wiki/Ants-Starter-Pack-Guide which states: "The objective of the starter bots should be to be as helpful as possible for beginners who may not be able to do their own rewrite. It should also showcase good readable design and best practices for the language."

Dumping all code in one source file and all project files in one directory is neither good readable design and best practice for any language, nor is it helpful for beginners.

**Comment by Janzert** [comment]
I think what Aerique and McLeopold are discussing is different from what Amstan was originally referring too. In regards to having a bot laid out such that there are subdirectories with source files in directories below the MyBot.ext source file. This should already work, and in fact the current common lisp starter bot does compile fine currently. With regards to whether or not starter bots should do this; I think whatever is natural for the language to meet the starter bot specs given is the way to go. But I don't have strong feelings on it either way.

But I believe what Amstan was originally referring to in this bug is something completely different. I believe Amstan meant the case where the bot is sent in an archive file containing one directory at the root and all of the submissions files and directories contained within it. This is a fairly common way to create zips and I believe the only way to have a tar file. In the past compile_daemon.py took care of detecting this case after unpacking a submission (if it found only a single directory within the archive it moved all contents of it up to the root and deleted that directory, see lines 66-69 [here](https://github.com/aichallenge/aichallenge/blob/a1b56bda7cee793ebda808f30fb8ddd8be765290/manager/compile_daemon.py)). I think the current compiler.py is the wrong place to handle this and it should be taken care of at the time the submission is unpacked. It seems this is handled in the worker.py Worker.unpack() method now.

**Comment by McLeopold** [comment]
I think the starter bots should be geared toward someone that is new to the language.  It should provide enough framework that they can immediately dive into the logic of the bot without having to worry about parsing input, displaying output, updating state and timing code.  The python and java bots do this by creating a class that has a do_turn function.  They clearly mark sections where variables will be remembered between turns, and sections where they will not.  They python bot is clearly split into 2 files, the bot logic and the framework code.  It is very easy to understand which file does what and doesn't over complicate things.

Aerique's bot provides much more than this.  While extremely useful, and it should be provided to contestants as an advanced lisp package, it is too much framework for a beginner and requires a lot of lisp experience to use.  I'm willing to concede that subfolders are okay, as long as it is understandable at a glance and doesn't detract from understanding the ants code.  If you have to follow too many references to different files, it becomes too much.  Anything more is a big hurdle to beginners.  If you find you really need the subfolders, then you might have too much framework.

Right now the compiler expects only 1 file named MyBot.\* to exist at the root of the zip where the extension declares the language.  Everything else goes as long as it doesn't break this.  I think most bot writers will be able to meet this requirement by putting a stub file in the proper place while maintaining a directory structure as well.

**Comment by amstan** [comment]
As janzert said. This bug is not about detecting code in subfolders for compiling. It's about a regression.

Code used to work(in tron/pw) when submitted these ways:
1. submission.zip > submission/ > MyBot.py
2. submission.zip > MyBot.py

Now, 1 is broken, so only 2 works.

This is important because most users right click on a folder, and press compress; this yields an archive similar to #1.
