### ISSUE TITLE
McLeopold's checklist: worker/engine -> visualizer

### ISSUE THREAD

**Issue by mleise** [aichallenge/aichallenge#14]
Here are some points you and I should finalize so that we can start to watch replays:
- Drop the full state information for food.
- Decide on wether to drop the full state information for ants (usually 50% of file size; not a blocker, but don't forget :) )
- Player colors set by the replay.
- Give information on when a bot crashed. (playerNcrash <turn>?)
- Update the specs page where neccesary.

**Comment by McLeopold** [comment]
I've been thinking about the replay files.  Originally I wanted the replays to be able to be run through a bot.  Given the fact that each bot gets different info because of fog of war, I've given up on this idea.  That left us with changing the bot input spec slightly to make it usable as a replay spec.  The latest big change is dropping food and putting in a 'D' line when it disappears.  Since we have deviated significantly from bot input, I'm thinking we ought to just redesign the replay file to be efficient.

Here a totally new format for replay that I propose.  In general, an ant is created at a specific turn, moves around, and then dies.  Ants have owners.  Food is created at a specific turn, and is then removed or turned into an ant.  Water is always there.
1. Variables will be at the start.
2. Char map will be next.
3. List of food in the following format:
       # ant owner is redundant, I'm predicting you would want it :)
       F row col startTurn endTurn antOwner?
       F 2 3 0 30 0
       F 5 5 0 20 - # a '-' is food disappearing due to conflicting ants being in range
4. List of ants in the following format:
       A owner startRow startCol startTurn endTurn directionList
       # endTurn is redundant, but helps make sure the directionList is the correct length
       A 0 3 4 0 20 neeee--wwwwswswsssss # a '-' char is an ant not moving
5. score line at end of file
       score 14 23 31 76
6. player ending status in the following format:
       playerXstatus lastTurn status # status could be any string with spaces
       player0status 20 eliminated
       player1status 30 timeout
       player2status 40 crashed
       player3status 40 survived # multiple bots may be alive at turn limit

The parse should be able to parse this into a more generic data structure for replay.  Also, there should be a function to return a bot's input for a turn, similar to the game state extractor from the last contest.  This would require calculating the view distance for each bot.  The engine would also have a feature to take an input file and output a players input stream to a bot, for testing.

I know you want to do various effects depending what happens in the game.  Let me know if this format would get you the information you need.

**Comment by McLeopold** [comment]
Mostly fixed by sigh.  Additional problems should be new issues.
