### ISSUE TITLE
Invalid replays because ant length is 1 short

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#145]
When a bot crashes or times out, all its ants have the incorrect length for moves.  There are various quick fixes, such as ignore it, append a no move (dash) to the list, subtract 1 from the length.  I'd like someone to think of a good solution that isn't a hack that makes sense.

**Comment by aerique** [comment]
Both adding a "no move" and subtracting 1 from the length sound reasonable.  My preference would be the latter since the bot's turn is illegal and should not be counted.

_edit:_ from my limited test set (one local game and one on the test server) I don't see what you mention happening.  For a crashed player I see all its ants outputting "no moves" until the game's end.

Have you got a link to a specific example?

**Comment by McLeopold** [comment]
The error actually happened when a timeout or crash happened in the last turn.  Finish turn was not getting called correctly for the remaining bot.
