### ISSUE TITLE
Sandboxed compilation

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#15]
Compilation should be sandboxes.
I have heard of a few loopholes during the last contest: some compilers allow code execution at compile time.

jmcarthur has successfully proven this with haskell.
Even though we patched that haskell problem, I heard that this is also possible with CL.

They might be possible with others as well. Instead of risking it, I propose to sandbox the compilation step as well.

**Comment by amstan** [comment]
Is this done? @Mcleopold @Janzert

**Comment by aerique** [comment]
_edit: I should have used the compiler arguments from compile.py :-(  Anyway, I'm at work currently so I can't rerun the tests right now._

The following starter bots compiled and handled the [sample bot input and output from the wiki](https://github.com/aichallenge/aichallenge/wiki/Ant-bot-input-output).  I did not use the `-j` option, since it would take too much configuration on my work machine (so I don't know how relevant this test is):
- C++ (`sandbox.py make`)
- Common Lisp (`sandbox.py "sbcl --script MyBot.lisp"`)
- Java (`sandbox.py make`)
- OCaml (`sandbox.py "ocamlbuild MyBot.native"`)

Did not compile:
- Scala (`sandbox.py "scalac *.scala"`): did not produce any class-files.

Untested:
- C (empty dir)
- D (D compiler not available for my dist)
- Go (no idea what to set GOROOT to after installing gccgo-4.6)
- Haskell (empty dir)
- JavaScript (interpreted)
- LOLCODE (compiler(?) not available for my dist)
- Perl (interpreted)
- PHP (interpreted)
- Python (interpreted)

**Comment by amstan** [comment]
Yes, but is it actually in effect in worker.py?

**Comment by aerique** [comment]
Not by the looks of it.
