### ISSUE TITLE
"Bad submission key found"

### ISSUE THREAD

**Issue by aerique** [aichallenge/aichallenge#166]
Since making an additional account "lispstarterbot" I can no longer submit bots with either that account or "aerique-test".  I always get a "Bad submission key found" message.

The major problem is that there are no further error messages or explanations on how to solve this issue: neither on the page with the error message nor in my profile page.

**Comment by Janzert** [comment]
Tracked this down a little more with aerique. Something about the common list starter package zip from the beta server is causing line 52 of check_submit.php to trip. This was tested with multiple browsers by myself and aerique with all of them displaying the problem so it seems like it is something server side that is going wrong. At the same time I'm not sure how the data being uploaded is causing a modification of another field in the request.

**Comment by McLeopold** [comment]
The max_post_size of 8M is being exceeded and the $_POST array is then empty.  I'm checking on the best way to handle this.  I've increased the limit to 12M and gotten a correct message.

The lisp file is too large because I was testing the compile in the starter pack dir and left it there, so it probably got picked up by the starter pack make file.  I've cleaned this up.
