### ISSUE TITLE
Trueskill - needs to be consistent between ranking and profile

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#180]
Currently the Trueskill shown on the ranking page differs from that shown on the profile.
I believe this is because the sigma is gradually decreasing after any game played in the system.

However, if I understand the algorithm correctly then we shouldnt be reducing sigma for players who are not competing in the games.  The sigma reduction should happen for the people who are in the game to be ranked, but not for others. It says "you might have changed skill since I last saw you, so I'll increase the margin of error"
Otherwise we are basically saying "every time we don't give your bot a game, we lower it's ranking" which is a terrible thing to do to people when they have no control over getting another game.

Either remove the sigma drop for games you do not compete in or reduce it significantly (or fix the scheduler so the time between games is small enough not to impact the ranking).
Regardless, show the same ranking on both pages.

**Comment by McLeopold** [comment]
This is different because the ranking list is generated every 2 minutes and lags behind the actual submission data.  The idea was to not go directly against the submissions table to reduce mysql load.

**Comment by zaphus** [comment]
I think it's more than just the delay, if it were just a delay then you would see a constant score a little behind - but it wouldnt change until you played again, we're also seeing it slowly drop over time on the ranking page (or were, I havent checked today - something changed based on the increases in rankings across the board)

**Comment by McLeopold** [comment]
There is only a problem if mu changes outside of a game report.  Right now I don't think there is any issue.

Here an explanation to give you some insight into the values being used.

The database calculates the new mu/sigma at the time a game is finished and reported.  The old values come directly from the submission table, which is where the rankings draw their values.  The submission table is then updated with the new values.  We record a history of all skill updates.  There are 3 possible places to find a skill value using the website that draw from 3 different places and can all possibly be different.

1) The ranking table is calculated once every 2 minutes.  This skill value will be a bit behind.  Sigma increase happen after the table is build, so the submission will never match this value exactly.
2) The submission table has the _real_ value, or the one that gets updated and is used for all calculations.  This is the value that really matters and you will see it on your submission page.  This is the most up to date.
3) The game replays and game_player tables contain what was the skill at the time the results where reported.  This can be used to see a history of your skill and how individual matches affect it.  This will be mostly accurate, but may not reflect the most recent sigma increase.

For normal trueskill, the players' skills do change over time as they learn and improve.  This will not be the case for static coded bots.  We've chosen to increase sigma based on new submissions rather than time since last game.  The thought is that a submission should find a place relative to the rest of the field and never move from that spot since it can't improve it's own code.  Only when the field of players changes would we want the submission to find a different mu.

Note that an _increase_ in sigma is a _decrease_ in skill, because skill is mu - sigma \* 3.  This means your skill can drop even without getting any games, which is okay.  You don't lose any mu.  Your greater sigma allows you to gain skill faster once you do get a game.

**Comment by zaphus** [comment]
Makes sense, except that the end user won't care about any of that...  they will see their rating drop while not getting any games.  This is a double whammy for them, those who happen to not get games will miss out on games which sucks, and also drop in rating which sucks even more.

Highlights the need to get the match seeder working properly, it still behaves unfairly (some bots getting multiple games per hour while others get nothing for many hours)

However if this is all behind the scenes and the rating on the main page stays static until their next game, that will reduce the complaints.

**Comment by McLeopold** [comment]
If we fix anything, it would be making the ranking page more dynamic.  Calculating the rank does take some effort, so I'm not keen on doing this for each incoming request.  Having the submission page show the most recent skill is nice because you can get realtime info about how the matches affect your skill.

I'll consider moving the sigma increase to just before a game result updates the skills, and only for those players.  It will be based on new submissions since that users last game.

Seeding is really broken, but let's keep that discussion in the other issue.

**Comment by McLeopold** [comment]
Okay, I think this issue is obsolete.  Rankings are now calculated per game and results in the rankings list should match the submissions pages.  Bots will still drop in rank due to other games they don't participate in, but this would happen no matter what system we used.
