### ISSUE TITLE
Write debugging howto.

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#188]
This will be different for every language.  I expect each language would want to detail the following
- writing log files
- setting breakpoints

Breakpoints can be troublesome.  If you capture bot input/output and run it back through the bot with redirection, you aren't dealing with sandbox code and it becomes easier.  At some point, people may want to try to debug while a game is running live, which means attaching to the bot process somehow.  It would be nice if language experts could detail some of this info for others.
- attaching to running process

**Comment by xarg** [comment]
Attaching to the running process? You mean like strace or something? If that's the case I'm not sure how useful this will be. 

By defining a clear example on how to use certain logging modules for different languages will be quite useful. For example in python the logging module can be used to debug a running bot since stdout is busy with the actual game communication. In python I would also use a logging configuration file that will setup my logging depending on where my program is running (locally or on the server).

**Comment by amstan** [comment]
A lot of people seem to have good results with attaching debuggers to their bots. Languages like C,C# and so on.

In order to do this, they must raise the timeout limit for the engine, so the bot doesn't crash when it breaks at a breakpoint.
