### ISSUE TITLE
change "next game" on player pages to indicate number of games or time until next game

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#194]
Currently the 'next game' on the player pages has a hardcoded string

With the new seeding method it will now be possible to say:
"Next game in no more than %d games time"  (or something like that)  - since we know the maximum number of games that will happen before you become the seed again (in fact it will usually be 1/4 or less of that number, but err on the high side)

Since we know approximately how many games we get played per hour (it's in the stats) then it could even say
"Next game in around %d minutes"    where the value is    (#games_until_seed \* games_per_hour)*60

note that this will prompt people to refresh the page a bit :-)

**Comment by Janzert** [comment]
a bit of an aside but this is the way it worked during planetwars

**Comment by zaphus** [comment]
I see some progress has been made on this:

Current Rank: 4

54 players are ahead of you.
The current game rate is about 6.233333333 players per minute.
Your next game should be in about 7.246434938741342331000000000000 minutes.

My Feedback:   truncate the numbers, obviously :-)
Include  a "Next Game" header before "54 players ahead of you"

**Comment by obeleh** [comment]
The "Your next game should be within X minutes" is off. I think this is because the game rate is based upon the participating players per match  (since there is a join with game_player:

select @players_per_minute := (select count(*)/30
                from game
                inner join game_player
                    on game.game_id = game_player.game_id
                where timestamp > timestampadd(minute, -30, current_timestamp)
               )

As far as I can see the matching up doesn't only pick players that are in line ahead of you. Probably more related to their skill and rank. Then the easiest way to calculate players_per_minute would be a worst case scenario calculation. 

The worst case scenario would be that all other players (ie. not the seed player) would be behind you in the queue. Which would mean that players_per_minute should be seed_players_per_minute:

select @seed_players_per_minute := (select count(*)/30
                from game
                where timestamp > timestampadd(minute, -30, current_timestamp)
               )

This way the estimate is an upper bound like the line "Your next game should be within X minutes" suggests.

**Comment by McLeopold** [comment]
It works good enough.
