### ISSUE TITLE
Duplicate games being scheduled

### ISSUE THREAD

**Issue by zaphus** [aichallenge/aichallenge#196]
There are instances of the same match being scheduled twice (different ID, but the same bots and map)
this started happening after multiple worker instances were created, but may be unrelated

Examples: 
28990 and 28991
29014 and 29030

Possibly unrelated, but worth mentioning:
sir_macelon has had almost all it's current run of games on 4 & 5 maps 
I realise that is probably random luck, but there could be more to it

**Comment by McLeopold** [comment]
The map are chosen based on the seed player, so the seed player should be seeing a new map.  I never did add in the logic to pick opponents based on map.  We could perhaps choose the map after the opponents are selected.

With the switch to choose a player based on the last time they played a game, rather than the last time they were a seed, some of our checks and balances will not work anymore.

**Comment by zaphus** [comment]
Every game since midnight (server time) has been the same - the top 5 players playing on map 22, no other games have played that I can see.  Timewise this lines up with the McLeopold commit about 2 hours ago.

http://aichallengebeta.hypertriangle.com/profile_games.php?user=78&page=1

here's a sample:

22 Jun 1:56

84.21

(1)OlexandrT(2)Zaphus(3)FlagCapper(4)sir_macelon(5)antimatroid

2nd of 5

symmetric_22

Game »

22 Jun 1:54

84.04

(1)FlagCapper(2)OlexandrT(3)sir_macelon(4)Zaphus(5)antimatroid

4th of 5

symmetric_22

Game »

22 Jun 1:53

84.18

(1)OlexandrT(2)sir_macelon(3)FlagCapper(4)Zaphus(5)antimatroid

4th of 5

symmetric_22

Game »

22 Jun 1:51

84.31

(1)sir_macelon(2)Zaphus(3)FlagCapper(4)antimatroid(5)OlexandrT

2nd of 5

symmetric_22

**Comment by McLeopold** [comment]
Recent changes should have taken care of this.
