### ISSUE TITLE
map in replay data is not the initial map

### ISSUE THREAD

**Issue by Janzert** [aichallenge/aichallenge#197]
The map as recorded in the replay data is not the initial map with ants and food setup as it is on the first turn. It appears to be the final state of the map but I'm not positive that is the case.

It would also be really nice if the replay recorded the server name for the map.

**Comment by mleise** [comment]
When we first agreed on the format the only relevant data from the map, was where the water is. iirc at this point the map had some food items in addition to the player starts, both of which the visualizer ignores. In this situation we agreed on using some 'interesting' turn for the replay map, so you could use it like a jpeg thumbnail in a potential replay browser application where the initial map is not enough to distinguish several replays on the same map visually.
So much for the reasoning behind it. Any other use of the land squares is ok on my side.

**Comment by McLeopold** [comment]
The replay contains this for a server name:

"location":"aichallengebeta.hypertriangle.com"

The map is not supposed to be the starting state.  It will be either the final or the most significant turn as defined by the "won at" code.  This is so that a thumbnail could be created that would represent the game, not just the map.
