### ISSUE TITLE
Revert the Header Size

### ISSUE THREAD

**Issue by aarossig** [aichallenge/aichallenge#285]
I created the original design of the site. I am not happy with the new header.

The height is far too short in proportion to the size of the navigation bar on the left. I tested the original design on varying screen resolutions. The vertical space that is used for the title doesn't interfere with the content. It looked good right down to my 1024*600 Netbook.

**Comment by amstan** [comment]
I don't like the new change either.
A few other people on irc agree with me too.
- Maybe make it 150px if you really want to shorten the header.
- Sign in should stay in the header, it keeps things balanced.
- Do not have overlapping things, it looks weird
- What's with the white shadow?

**Comment by McLeopold** [comment]
The front page content isn't really set yet.  I think we should put in some effort to make a great landing page first.  After that, we can decide what should be above the fold and define the height from that.

If the large header looks best on the front page, I suggest making a smaller header for all the other pages.  It was shrunk because too much space was being used up, causing constant scrolling for every other page visited.  Most visitors will be returning contestants checking on their ranking and uploading code, and really don't care for half their page to be a giant header that they've already memorized.  Front page is okay, but not the others.

Read "Don't Make Me Think" by Steve Krug.  http://www.sensible.com/dmmt.html

The sign in | sign up makes much more sense being placed with the rest of the menu.  It is not balanced to have 1 element out of place.  Elements that are related logically should be related visually.  Also, pages should be broken up into clearly defined areas.

Things we still need to do for the home page:
- Create a better site identity (logo?)
- Convey the big picture idea (why am I here?), with pictures
- Big colorful "Sign Up" button (should be implemented after login cookies)
- Create a tag line
- Provide an overview of the site heirarcy
- Provide better search tool besides just username

**Comment by Janzert** [comment]
As of a few minutes ago the header height is now 50% of the sidebar width. I really don't like the idea of expanding the header back to almost the same height as the sidebar is wide (although it never was quite the same that I see). I'd much rather keep as much useful content space above the fold as we can, even for the front page.

**Comment by aarossig** [comment]
@McLeopold -- Yeah, I understand where you are coming from in regards to the scrolling issue. In the end, most of our traffic will be return visits and for those guys, HTML with no styles would probably suffice, but it is about making it aesthetically pleasing. I merely feel that it looked very eye-catching with the large header. I have far more experience with print design, but if I can use the term unity in this context. It made the page come together.

Now.. for the useful component of this comment. What if we have a "splash-page" (don't hound me, continue reading) for non-logged in users. I say we take a page from Facebook's book. When you visit Facebook as a non-logged in user, you are presented with a beautiful page that grabs your attention with globally connected people illustrated through a world map.

Once the user is signed in, we can make the design more functional than practical. In this case we can play with header size and possibly create some kind of alternate "power-user" interface that gives them the bare minimum (kind of like top vs. htop).

**Comment by McLeopold** [comment]
The large header _did_ look nicer.  A splash page would be awesome.  I'll get a login cookie working, so it can work well for the regulars.

**Comment by aerique** [comment]
It's not just the size that was changed but someone tarted it up with lighting effects that makes it look cheap instead of professional.

**Comment by Janzert** [comment]
The only extra "lighting effect" that wasn't there before is the glow behind the word Ants. The rest of it has been there for the last few months at least.

**Comment by amstan** [comment]
aarossig told me that he likes the header look now. So I'll close this.
