### ISSUE TITLE
Ants starter packages

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#3]
We need as many starter packages as possible.
## Documentation

Some sample bots can be found in the [repo](https://github.com/aichallenge/aichallenge/tree/epsilon/ants/bots).

There should be valid documentation in the [wiki](https://github.com/aichallenge/aichallenge/wiki/Ants-Game-Specification).
## Versions

Regarding Compiler/Interpreter/Runtime versions, the first available should be preferred:
- Ubuntu 11.04 amd64 repository (main multiverse restricted universe)
- Ubuntu PPA
- .deb files
- source files
- binaries

This is not a strict list, but it would make it much easier to install the language/starter pack.

**IMPORTANT: If you do want a language to be supported**, please modify `worker_setup.py`, `compiler.py`. Check IRC for more details.
## Files
- See `ants/dist/(starter_bots|sample_bots)` for the bots.
## Voluntering

Comment here to volunteer, then get started making it. We'll accept either:
- Fork the repo, add your starter pack in a folder, then submit a pull request
- Make a new repo, we'll add it as a submodule

**Comment by ZogStriP** [comment]
I can do the .Net (C#/VB) starter packages if interested.

**Comment by amstan** [comment]
Sure, check the OP again, I gave you some links to the docs and some already finished bots.
If you're doing C#, you could start from the java ones, since they're closest.

**Comment by aerique** [comment]
I can do the Common Lisp starter package.

**Comment by lavalamp** [comment]
I can do a golang starter package.

**Comment by lavalamp** [comment]
Question, how advanced should starter packages be? For example, would it be frowned upon if I added logging/replay features to my package? Is the point of the starter package to just get people started or to make some base code that's as useful as possible? The existing ones are pretty basic, but I'm not sure if that's intentional or just because there is limited time to do things in.

(I mostly completed my starter package but haven't yet been able to test it, playgame.py was failing on me. I suspect my setup. I will probably find time to finish it on Sunday the 6th. You can see my fork for a preview.)

Also, I will make a (separate) change in my fork to the worker build script to grab a more recent version of golang, hopefully you can pull that, too.

**Comment by amstan** [comment]
Reply to lavalamp

It doesn't matter how advanced it is, just make sure stuff works, and it's easy for beginners to use or ignore the particular feature.

We'll pull everything when it's ready.

**Comment by VagabondEx** [comment]
Please, with the starter packs, also specify the language versions which are used in the executing environment. With the compiled languages it is apparent when it doesn't compile because you used some new language construct, but it can cause very mysterious problem with script languages, such as, in my case, Python.

**Comment by amstan** [comment]
VagabondEx: I updated the OP, please refer to the _Versions_ section.

**Comment by VagabondEx** [comment]
Thanks!

**Comment by Naktibalda** [comment]
I can do a PHP starter package

**Comment by Synesso** [comment]
First cut of Scala package done. Pull request issued. Looks shiny but is probably broken. Adding some tests shortly.

**Comment by TJC** [comment]
I'm just coding up a Perl starter package now.

**Comment by McLeopold** [comment]
It would be nice to have a "getting started" section for each language at some point with instructions on setting up a basic programming environment.  Some starter bots include more than the standard packages (or whatever the language's terminology is) and might be confusing for someone just starting out.  _cough_ common lisp _cough_

Also, _please_ dumb down the starter packages to the appropriate level and _do not_ include tools.  A tool is anything that would not be needed for the starter bot to run on the official server.  We can create language specific tool packages in a separate download for that.

**Comment by aerique** [comment]
I've trimmed the _cough_ Common Lisp _cough_ starter package.

**Comment by Synesso** [comment]
Happy to write the getting started bit for the Scala bot. It will be quite simple. Where do you envisage this going? Wiki or readme in source?

**Comment by amstan** [comment]
> Happy to write the getting started bit for the Scala bot. It will be quite simple. Where do you envisage this going? Wiki or readme in source?

I would recommend you stick with readme.md in your starter bot folder.

**Comment by Synesso** [comment]
Done. I copied the most excellent common lisp one. Pull requested.

**Comment by amstan** [comment]
I'm going to be closing the issue for statistic's sake as we have a ton of starters already. Feel free to continue submitting them.
