### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by truell20** [aichallenge/aichallenge#395]
My name is Michael Truell. I am part of a team that has developed an internal programming competition for Two Sigma, a large quantitative hedge fund. We are looking to open up the competition to the greater public. The competition was originally inspired by the Ants, and we have been in contact with UWaterloo about making it a part of the AI Challenge series. We are wondering if anyone on the Ants team would be willing to answer a few of our questions about administrating a large, public competition either over email, on a call, or on this thread.

We've spoken with one of the planet wars devs, @DanielVF, but would like to anyone involved with Ants as well.

**Comment by DanielVF** [comment]
Just as a note, I had a good phone conversation with Michael about the Planet Wars era lessons learned.

**Comment by DanielVF** [comment]
You can see a visualization of Michael and Co's game here: http://halite.io/website/game.php?replay=1470694919-3628009908.hlt

**Comment by Janzert** [comment]
I'm sure no one is saying or acting with any ill intent but I just wanted to note that almost certainly UWaterloo is the wrong entity to be talking with in order to get permission to run something under the AI Challenge name. The contest's that were run under any affiliation with UWaterloo were actually run under another name. Unfortunately the correct contact for permission isn't actually entirely clear. Jeff Cameron is the person that was at least theoretically in charge, but he was and has been quite difficult to contact. I believe that it is Alexander Stan who currently holds the domain name and almost positive that he runs the archived sites (although all except ants seem to be returning 500 errors). The confusion over ownership is one thing that holds me back from trying to resurrect AI challenge. If I ever did decide to run something like it in the future I would probably just start with a fresh name/organization.

Finally, one recurring theme in scaling the contest was the SQL server ending up as the bottleneck.

**Comment by truell20** [comment]
@Janzert Did you guys end up using multiple SQL servers?

**Comment by Janzert** [comment]
Sorry, got busy and didn't get back to this.

Web server, sql server, worker management, etc. were all done from a single server. Each bottleneck was resolved as we ran up against it by modifying what or how we were doing things. The only part moved out to multiple servers were the actual games being played.

**Comment by truell20** [comment]
@Janzert Thank you for the response! 

Is there any chance of licencing the auto compile script within about a month? We use a modified version of it in our project and will have to rewrite it from scratch if no license is applied.

**Comment by Janzert** [comment]
See my answer on issue #276

**Comment by truell20** [comment]
@Janzert Did you guys have any security issues?

**Comment by Janzert** [comment]
Since I knew our sandbox for running programs had holes in it this was a concern throughout the contest. Fortunately we never had any issues materialize.

**Comment by DanielVF** [comment]
@truell20 and friends did an amazing job with the Halite Challenges https://halite.io/ 

Definitely worth checking out if you love the genre.
