### ISSUE TITLE
engine needs to attempt to read all bot input before timing check, but not too much

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#59]
In the last contest there was an infinite loop checking for bot input and the current time as much as possible.  I changed this to sleep a little before checking for bot input.  Then because the engine only tried to read 1 line at a time, bots were timing out.  So I changed this to read all bot input available during 1 iteration.

This would allow a misbehaving bot to fill up the pipe and cause the engine to stall.  We need to find a balance number of lines to read without checking every nano-second.

**Comment by mleise** [comment]
The pipe wont have a buffer of several megabytes. On my system it seems to be 64k. So there is no risk of a bot writing more than 64k in one iteration and Python can easily handle that.

**Comment by McLeopold** [comment]
But, a bot could write continuously without ever sending a go, so we want to limit the engines memory as well.

**Comment by sigh** [comment]
Now engine reads up to 100 lines per iteration.

**Comment by mleise** [comment]
What does limiting the number lines help then if the continuous stream of data doesn't contain a \n?

**Comment by sigh** [comment]
Well worker/engine.py doesn't even see the output until an entire line available, so if there is a problem it is isolated to worker/sandbox.py. I don't think sandbox.py ever blocks on reading so it doesn't seem to be an issue... but reading the code I'm not exactly sure about what it _does_ do. I will talk to McLeopold/janzert about it later.

**Comment by mleise** [comment]
Just slightly related, but since I talked with you sigh and McLeopold about it I'll link this article I found through stackoverflow.com: http://home.gna.org/pysfst/tests/pipe-limit.html
In short: Since kernel 2.6.11 the kernel can allocate up to 16 pages (4k) of memory to a pipe. I/O-operations are only guaranteed to be atomic if they are <= 4k. So if someone writes 8k, the data may end up in the receiver as 2 reads of 4k.
The link explains **deadlock issues with Python** and how the author tried to work around them.
