### ISSUE TITLE
prepare for leap seconds

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#60]
In case a leap second is declared and the ntp updates during a game, a bot may get extra time to process moves giving them an unfair advantage.  The engine should be updated to account for this.

**Comment by sigh** [comment]
Does this really warrant development effort?

There have been like 24 leap seconds in the ~30 years since their introduction. Further, leap seconds occur on Dec 31 and Jun 30, and a June leap second would have been announced by now. Regardless, leap seconds are usually announced months in advance which allows plenty of time to implement something in the event of an announcement.

There is also the solution of just not running the engine during that second.

**Comment by aerique** [comment]
Agreed with sigh.  This sounds like over-engineering.

Save it for a quiet time between two contests.

**Comment by amstan** [comment]
I agree with closing this.
One second for a few bots shouldn't matter that much.

**Comment by sigh** [comment]
I'm closing this as wontfix.
