### ISSUE TITLE
Visualizer Score

### ISSUE THREAD

**Issue by McLeopold** [aichallenge/aichallenge#99]
The visualizer score graph does not include the food bonus at the end in the graph.  There isn't an obvious way of declaring the winner either.  Perhaps an asterisk by the name, or underlined?  Or, dare I say it, double-underlined?

This may be because there are to location in the replay for scores that might not be consistent:

```
{ score: [5,20], // this is the final score
  replaydata: {
    scores: [[0,1,2,3,4,5], // this is the running score
             [0,1,2,3,5,8]
  }
}
```

**Comment by mleise** [comment]
Double underline sounds good, but is not supported by the HTML canvas as far as I know. (It has to be something you can put on a CSS font property line.) Doing it manually doesn't work well either, because browsers tend to have differing interpretations of the y-offset. So an underline may appear too close or too far away from the text. I will most probably use the asterisk if I cannot get underlines to look good.
